---
server:
  port: 8080

  httpProxy:
    enabled: true
    port: 8443

db:
  host: localhost
  port: 5432
  username: chorerewards
  password: supersecretpassword
  name: chorerewards

auth:
  key: averylongsecretthatissecure
